version: '3'

services:
  web:
    build: .
    command: daphne backend.asgi:application -p 8000 -b 0.0.0.0
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
     - .env

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  tests:
    build: .
    command: python manage.py test
    volumes:
      - .:/app
    depends_on:
      - redis